spring.application.name=details
# MySQL Database Configuration
SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/employee_db
SPRING_DATASOURCE_USERNAME: root
SPRING_DATASOURCE_PASSWORD: rootpassword
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.initialization-fail-timeout=-1

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect